chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('unread_rooms/', views.unread_chat_rooms, name='unread_rooms'),
    path('<str:user>/', views.room, name='room'),
    path('', views.index, name='index'),
]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from mainapp.view import login, home, add_manager, add_customer, \
    add_purchase, call_notes, attachments, task, calendars
from mainapp.view.import_export.export_data import export_xls, import_xls
from mainapp.view.pdfs import offers


app_name = 'mainapp'
urlpatterns = [
    path('', include(('mainapp.urls2', 'mainapp'), namespace='new')),

    path('heartbeat/', login.heartbeat, name='heartbeat'),
    path('', login.LoginView.as_view(), name='login'),
    path('logout', login.logout_view, name='logout'),

    # Home
    path('old/home/', home.HomeView.as_view(), name='home'),
    path('home/customer/<customer_id>/', home.CustomerHomeView.as_view(), name='customer_home'),

    path('manager/', add_manager.CreateManagerView.as_view(), name='add_manager'),
    path('manager/<int:pk>/', add_manager.UpdateManagerView.as_view(), name='edit_manager'),
    path('delete_manager/<manager_id>', add_manager.delete_manager, name='delete_manager'),

    path('customers/', add_customer.ListCustomerView.as_view(), name='list_customer'),
    path('customer/', add_customer.AddCustomerView.as_view(), name='add_customer'),
    path('customer/<int:pk>/', add_customer.UpdateCustomerView.as_view(), name='edit_customer'),
    path('update_customer/<int:pk>/', add_customer.update_customer, name='patch_customer'),
    path('delete/customer/<int:pk>/', add_customer.DeleteCustomerView.as_view(), name='delete_customer'),

    path('add_purchase/', add_purchase.AddPurchaseView.as_view(), name='add_purchase'),
    path('purchases/', add_purchase.ListPurchaseView.as_view(), name='list_purchase'),
    path('purchases/<int:pk>/', add_purchase.UpdatePurchaseView.as_view(), name='edit_purchase'),
    path('update_purchase/<int:pk>/', add_purchase.update_purchase, name='patch_purchase'),
    path('delete/purchases/<int:pk>/', add_purchase.DeletePurchaseView.as_view(), name='delete_purchase'),
    
    path('task_list/', task.TasksView.as_view(), name='open_task_list'),
    path('task/<int:pk>/', task.TaskUpdateView.as_view(), name='edit_task'),
    path('delete/task/<int:pk>/', task.DeleteTaskView.as_view(), name='delete_task'),
    path('mark_complete/<int:pk>/', task.mark_completed, name='mark_completed'),
    path('create_calendar_task/', task.create_task, name='create_calendar_task'),

    path('call_notes/<customer_id>/', call_notes.CallNotesCreateView.as_view(), name='add_call_notes'),
    path('call_notes/<customer_id>/<int:pk>/', call_notes.CallNotesUpdateView.as_view(), name='edit_call_notes'),
    path('delete/call_notes/<customer_id>/<int:pk>/', call_notes.CallNotesDeleteView.as_view(), name='delete_call_notes'),

    path('chat/', include(('chat.urls', 'chat'), 'chat')),

    path('<int:customer_id>/attachments/', attachments.AttachmentCreateView.as_view(), name='add_attachments'),
    path('<int:customer_id>/attachments/<int:pk>/', attachments.UpdateAttachmentView.as_view(), name='edit_attachments'),
    path('delete/<int:customer_id>/attachments/<int:pk>/', attachments.DeleteAttachmentView.as_view(), name='delete_attachments'),
    path('email/<int:customer_id>/attachment/<int:pk>/', attachments.email_attachment, name='email_attachment'),

    # attachment type settings
    path('attachment_type/', attachments.UpdateAttachmentTemplateView.as_view(), name='attachment_type'),

    # calendar
    path('calendar/', calendars.calendar, name='calendar'),

    # export and import urls
    path('export_data/', export_xls, name='export_xls'),
    path('import_data/', import_xls, name='import_xls'),

    path('offer/<customer_id>/', offers.download_offer, name='pdf_offer'),
    path('offer_confirm/<customer_id>/', offers.download_offer_confirm, name='pdf_offer_confirm'),
    path('install/<customer_id>/', offers.download_install, name='pdf_install'),
    path('invoice/<customer_id>/', offers.download_invoice, name='pdf_invoice'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

windows_crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/models.py
import datetime

from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.db.models.aggregates import Sum, Count
from django.db.models.functions import Extract
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from mainapp.fields import ContentTypeRestrictedFileField
from mainapp.view.constants import CALL_NOTE_PRIORITY
from .usermanager import UserManager


# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_("First Name"), max_length=255)
    surname = models.CharField(_("Surname"), max_length=255)
    phone = models.CharField(_("Phone"), max_length=20, unique=True)
    username = models.CharField(_("Username"), max_length=255, unique=True)
    email = models.EmailField(_("Email"), max_length=255, unique=True)
    is_active = models.BooleanField(_("Active"), default=True)
    is_deleted = models.BooleanField(_('Deleted'), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(_('staff status'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['phone', 'first_name', 'email']

    def __str__(self):
        return self.first_name + " " + self.surname

    @classmethod
    def fetch(cls, username=None, user_id=None, is_superuser=False):
        try:
            if is_superuser is not None:
                user = cls.objects.filter(is_superuser=is_superuser)
            else:
                user = cls.objects.all()

            if username:
                user = user.filter(username=username).first()
            elif user_id:
                user = user.filter(id=user_id).first()

            return user
        except Exception as e:
            print("Exception occurs while fetching User: Error: {}".format(str(e)))
            return None


GENDER_CHOICES = (
    ('Male', _('Male')),
    ('Female', _('Female'))
)
PURPOSE_CHOICES = (
    ('Comapny', _('Company')),
    ('individual', _('individual')),
    ('Family', _('Family'))
)
OFFER_CHOICES = (
    ('Email', _('Via Email')),
    ('Letter', _('Via Letter')),
)
ATTACHMENT_TYPE_CHOICES = (
    ('offer', _('offer')),
    ('offer_confirmation', _('offer confirmation')),
    ('install', _('install')),
    ('invoice', _('invoice'))
)
CALL_NOTE_PRIORITY_CHOICES = (
    (CALL_NOTE_PRIORITY.high, _('Not started')),
    (CALL_NOTE_PRIORITY.medium, _('Pending In Work')),
    (CALL_NOTE_PRIORITY.low, _('Finished')),
)


class Customer(models.Model):
    first_name = models.CharField(_("first name"), max_length=255)
    offer_id = models.CharField(_("offer id"), max_length=255, blank=True,
                                null=True)
    invoice_id = models.CharField(_("Invoice ID"), max_length=255, blank=True,
                                  null=True)
    street = models.CharField(_("street"), max_length=500)
    postcode = models.CharField(_("postcode"), max_length=255)
    place = models.CharField(_("place"), max_length=255)
    surname = models.CharField(_("surname"), max_length=255)
    phone = models.CharField(_("Phone"), max_length=20, unique=True,
                             default='N.A')
    mobile = models.CharField(_("Mobile"), max_length=20, null=True, blank=True,
                              default='N.A')
    email = models.CharField(_("Email"), max_length=120, null=True, blank=True,
                             default='N.A')
    birthday = models.DateField(_("Birthday"), null=True, blank=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_deleted = models.BooleanField(_('deleted'), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    gender = models.CharField(_("gender"), max_length=100, choices=GENDER_CHOICES, null=True, blank=True)
    purpose = models.CharField(_("purpose"), max_length=100, choices=PURPOSE_CHOICES, null=True, blank=True)

    @classmethod
    def create(cls, first_name, street, postcode, place, surname, phone, mobile, gender, purpose):
        try:
            customer = cls.objects.create(first_name=first_name, street=street, postcode=postcode, place=place,
                                          surname=surname, phone=phone, mobile=mobile, gender=gender, purpose=purpose)
            return customer
        except Exception as e:
            print("Exception occurs while creating Customer. Error: {}".format(str(e)))
            return None

    @classmethod
    def fetch(cls, customer_id=None, name=None):
        try:
            customer = cls.objects.all()
            if customer_id:
                customer = customer.filter(id=customer_id).last()

            if name:
                customer = customer.filter(first_name__contains=name)

            return customer
        except Exception as e:
            print("Exception occurs while fetching Customer. Error: {}".format(str(e)))
            return None

    def __str__(self):
        return self.first_name + " " + self.surname


class CallNotes(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='call_notes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='call_notes')
    notes = models.CharField(_("notes"), max_length=1000)
    status = models.PositiveSmallIntegerField(choices=CALL_NOTE_PRIORITY_CHOICES,
                                              default=CALL_NOTE_PRIORITY.medium)
    created = models.DateTimeField(null=True)

    def save(self, *args, **kwargs):
        self.created = datetime.datetime.now()
        return super(CallNotes, self).save(*args, **kwargs)

    @classmethod
    def create(cls, customer_id, user_id, notes):
        try:
            call_notes = cls.objects.create(customer_id=customer_id, user_id=user_id, notes=notes)
            return call_notes

        except Exception as e:
            print("Exception occurs while creating Call Notes. Error: {}".format(str(e)))
            return None

    @classmethod
    def fetch(cls, customer_id):
        try:
            call_notes = cls.objects.filter(customer_id=customer_id)
            return call_notes

        except Exception as e:
            print("Exception occues while fetching Call Notes. Error: {}".format(str(e)))
            return None


class PurchaseRecord(models.Model):
    customer = models.OneToOneField(Customer, verbose_name=_("Customer"), on_delete=models.CASCADE,
                                    related_name='purchase_record')
    module_manufacturer = models.CharField(_("manufacturer"), max_length=255, null=True)
    watt = models.PositiveIntegerField(_("watt"), null=True, default=0)
    module_count = models.PositiveIntegerField(_("module count"), null=True, default=0)

    with_battery = models.BooleanField(_("with battery"), blank=True, default=False, null=True)
    manufacturer = models.CharField(_("manufacturer"), max_length=255, null=True, blank=True)
    kwh = models.CharField(_("Kw/H"), max_length=255, blank=True, null=True)
    manufacturer2 = models.CharField(_('Manufacturer'), max_length=255, blank=True, null=True)
    kwh2 = models.CharField(_('Kw/H'), max_length=255, blank=True, null=True)

    price_without_tax = models.FloatField(_("price without tax"), help_text=_("Price in Euro (€)"), null=True,
                                          validators=[MinValueValidator(0, _("Should be above 0"))],
                                          default=0)

    offer_by = models.CharField(_("offer by"), choices=OFFER_CHOICES, max_length=16, null=True)
    # OFFER INFORMATION
    offer_date = models.DateField(_("offer date"), blank=True, null=True)
    reseller_name = models.ForeignKey("Reseller", on_delete=models.SET_NULL,
                                      null=True, blank=True, related_name='purchases')
    declined = models.BooleanField(_("declined"), default=False, null=True, blank=True)
    # TECHNICAL DETAILS
    date_sent = models.DateField(_('date sent'), null=True, blank=True)
    project_planning_created = models.BooleanField(_('project planning created'),
                                                   blank=False, default=False)
    dc_term = models.DateField(_('DC Term'), blank=True, null=True)
    dc_mechanic = models.ForeignKey('Mechanic', on_delete=models.SET_NULL,
                                    null=True, blank=True, related_name='dc_purchases')
    ac_term = models.DateField(_('AC Term'), blank=True, null=True)
    ac_mechanic = models.ForeignKey("Mechanic", on_delete=models.SET_NULL,
                                    null=True, blank=True, related_name='ac_purchases')
    # INFORMATION FOR THE ROOF
    roof_type = models.CharField(_("roof type"), max_length=255, null=True, blank=True)
    roof_tilt = models.FloatField(_("roof tilt"), help_text=_("in Degrees"), null=True, blank=True)
    alignment = models.CharField(_("alignment"), max_length=64, null=True, blank=True)
    module_area = models.FloatField(_("module area"), help_text=_("Area in meter squared (m2)"), null=True, blank=True,
                                    validators=[MinValueValidator(0, _("Should be above 0"))],
                                    default=0)

    extra_details = models.TextField(_("extra details"), blank=True, null=True)

    # module_type = models.CharField(max_length=255)
    # memory_type = models.CharField(max_length=255)
    #
    # installation_date = models.DateTimeField()
    # cancellation = models.BooleanField(blank=True, default=True)
    # photo_roof_access = models.BooleanField(blank=True, default=True)
    # photo_counter_cabinet = models.BooleanField(blank=True, default=True)
    # video_counter = models.BooleanField(blank=True, default=True)
    # photo_of_counter = models.BooleanField(blank=True, default=True)

mainapp/forms/add_customer.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML

from mainapp.forms.mixins import LabelAdder
from mainapp.models import Customer, GENDER_CHOICES, PURPOSE_CHOICES


class CustomerForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['purpose', 'gender', 'first_name', 'surname', 'offer_id', 'invoice_id', 'street',
                  'place', 'postcode', 'phone', 'mobile', 'email', 'birthday']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # converting to string because form cannot handle date internationalization
        if self.instance and self.instance.id:
            self.initial['birthday'] = str(self.initial['birthday'])


class CustomerAddForm(CustomerForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'


class CustomerUpdateForm(CustomerForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[:len(self.fields.keys())//2 + 1]],
                css_class='col-md-6'
            ), Column(
                *[Row(field_name, css_class='form-group')
                  for field_name in list(self.fields.keys())[(len(self.fields.keys()) // 2 + 1):]],
                css_class='col-md-6'
            ),
        )

mainapp/forms/call_notes.py
from django import forms

from mainapp.forms.mixins import LabelAdder
from mainapp.models import CallNotes


class AddCallNotesForm(LabelAdder, forms.ModelForm):
    class Meta:
        model = CallNotes
        fields = ['notes', 'status']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        self.customer_id = kwargs.pop("customer_id", None)
        if not self.request or not self.customer_id:
            raise AttributeError("request missing")
        super().__init__(*args, **kwargs)
        for field_name in self.fields.keys():
            self.fields[field_name].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        instance = super(AddCallNotesForm, self).save(commit=False)
        instance.user = self.request.user
        instance.customer_id = self.customer_id
        instance.save()

mainapp/forms/search_user.py
from django import forms


class SearchForm(forms.Form):
    name = forms.CharField(required=True,
                           max_length=255,
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Search'
                               }
                           ))

mainapp/views.py
from django.shortcuts import render

# Create your views here.

mainapp/templates/home/home.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

<!-- Start 2nd section -->
{% block content %}
    <div class="container-fluid" style="padding: 0px 40px">
        <div class="row mt-5">
            <div class="col-md-12 col-lg-12">
                <div class="round-img text-center"
                     data-toggle="modal" data-target="#PurchaseModal"
                >
                    <div class="row">
                        <div class="col-md-3 col-lg-3 col-sm-0"></div>
                        <div class="col-md-3 col-lg-3 col-sm-6">
                            <img src="https://picsum.photos/seed/{{ customer.id }}000/200/200" class="vert-hori-center avatar-img rounded-circle"
                            alt="">
                        </div>
                        <div class="col-md-3 col-lg-3 col-sm-6">
                            <h3 class="pt-4">{{ customer.first_name }} {{ customer.surname }}</h3>
                            <p style="font-size: 12px; padding-top: 5px;">
                                <p>{{ customer.email }} | {{ customer.mobile }}</p>
                                <div>{{ customer.street }} {{ customer.place }} {{ customer.postcode }}</div>
                            </p>
                        </div>
                        <div class="col-md-3 col-lg-3 col-sm-0"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-6 col-lg-6">
                <div class="list-area home-card">
                    <ul>
                        {% if customer and customer.purchase_record %}
                            <li><a target="_blank" role="button" class="btn btn-primary btn-block" href="{% url 'mainapp:pdf_offer' customer_id=customer.id %}">{% trans "Offer" %}</a></li>
                            <li><a target="_blank" role="button" class="btn btn-primary btn-block" href="{% url 'mainapp:pdf_offer_confirm' customer_id=customer.id %}">{% trans "Offer Confirmation" %}</a></li>
                            <li><a target="_blank" role="button" class="btn btn-primary btn-block" href="{% url 'mainapp:pdf_install' customer_id=customer.id %}">{% trans "Installation" %}</a></li>
                            <li><a target="_blank" role="button" class="btn btn-primary btn-block" href="{% url 'mainapp:pdf_invoice' customer_id=customer.id %}">{% trans "Invoice" %}</a></li>
                        {% else %}
                            <li><a role="button" onclick="alert('Customer has no purchase record')" class="btn btn-primary btn-block" disabled>{% trans "Offer" %}</a></li>
                            <li><a role="button" onclick="alert('Customer has no purchase record')" class="btn btn-primary btn-block" disabled>{% trans "Offer Confirmation" %}</a></li>
                            <li><a role="button" onclick="alert('Customer has no purchase record')" class="btn btn-primary btn-block" disabled>{% trans "Installation" %}</a></li>
                            <li><a role="button" onclick="alert('Customer has no purchase record')" class="btn btn-primary btn-block" disabled>{% trans "Invoice" %}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="col-md-6 col-lg-6">
                <div class="" style="display: flex; flex-direction: column">
                    <div class="card">
{#                        {{request.session|get:'_language' }}#}
                        <a href="{% url 'mainapp:chat:index' %}">
                            <span>{% trans 'Chat' %} <span class="chat_badge"></span></span>
                        </a>
                    </div>
                    <div class="card">
                        {% if customer %}
                            <a href="{% url 'mainapp:add_call_notes' customer_id=customer.id %}">
                                <span>{% trans 'Call Notice' %}</span>
                            </a>
                        {% else %}
                            <a href="#">
                                <span>{% trans 'Call Notice' %}</span>
                            </a>
                        {% endif %}
                    </div>
                    <div class="card">
                        <a href="{% url 'mainapp:open_task_list' %}">
                            <span>{% trans 'To Do List' %}</span>
                        </a>
                    </div>
                    <div class="card">
                        {% if customer %}
                            <a href="{% url 'mainapp:add_attachments' customer_id=customer.id %}">
                                <span>{% trans 'Attachment' %}</span>
                            </a>
                        {% else %}
                            <a href="#">
                                <span>{% trans 'Attachment' %}</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- start modal section -->
    {% if customer %}
        {% include 'home/customer_purchase_modal.html' %}
    {% endif %}

{% endblock %}

<script>
</script>

</body>
<!-- =============== jquery-3.3.1.min.js =============== -->
<script src="{% static '/dashboard-assets/js/jquery-3.3.1.min.js' %}"></script>

<!-- =============== bootstrap.min.js =============== -->
<script src="{% static '/dashboard-assets/js/bootstrap.min.js' %}"></script>


<!-- =============== main.js =============== -->
<script src="{% static '/dashboard-assets/js/main.js' %}"></script>
</html>

mainapp/templates/home/search_customers.html
{% extends 'dashboard.html' %}
{% block maincontent %}
    <div class="dashboard-content-container" >
        <div class="dashboard-content-inner">
            <h1>Search Results</h1>
            <div class="tasks-list-container compact-list margin-top-35">
                {% for customer in customers %}
                    <div class="task-listing">
					<!-- Job Listing Details -->
                        <div class="task-listing-details">
                            <!-- Details -->
                            <div class="task-listing-description">
                                <h3 class="task-listing-title">{{ customer.first_name }} {{ customer.surname }}</h3>
                                <ul class="task-icons">
                                    <li><b>Phone - </b>{{ customer.phone }}</li><br/>
                                    <li><b>Mobile - </b>{{ customer.mobile }}</li><br/>
                                    <li><b>Place - </b>{{ customer.street }}, {{ customer.place }}</li><br/>
                                    <li><a href="#" id="{{ customer.id }}" onclick="customer_click(this)"><b>Select</b></a></li><br/>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <script>
        function customer_click(btn) {
            window.location = "{% url 'mainapp:customer_home' customer_id=1234 %}".replace(/1234/, btn.id);
        }
    </script>

{% endblock %}

mainapp/templates/home/search_form.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css" rel="stylesheet" />

<style>
    .search-bar {
        margin-top: -0.75%;
    }
    .search-button {
        position: absolute; top: 50%; left: 30px; transform: translateY(-50%);
    }

</style>

<div class="search-bar">
{#    <select class="form-control selectpicker" id="select-customer" data-live-search="true">#}
{#        {% for customer in customers %}#}
{#            <option data-tokens="{{ customer.id }} {{ customer.first_name }} {{ customer.email }}">{{ customer.name }}</option>#}
{#        {% endfor %}#}
{#    </select>#}
    <form method="POST" action="{% url 'mainapp:home' %}" style="position: relative;">
        {% csrf_token %}
        <input type="text" name="name"
               style="width: 50%"
               class="form-control" placeholder="Search" maxlength="255" required="" id="id_name">
        <div class="search-button">
            <i class="fas fa-search"></i>
        </div>
        <button class="button" type="submit" id="id_search_btn" hidden></button>
    </form>
</div>

<script>
    $(document).ready(function () {
        var input = document.getElementById("id_name");
        input.addEventListener("keyup", function (event) {
            // Number 13 is the "Enter" key on the keyboard
            if (event.keyCode === 13) {
                // Cancel the default action, if needed
                event.preventDefault();
                // Trigger the button element with a click
                document.getElementById("id_search_btn").click();
            }
        });
{#        $('.selectpicker').selectpicker();#}
    });

    $(function() {
      $('.selectpicker').selectpicker();
    });
</script>